"""
vba_runner.py - VBA macro generation and execution helpers for Word documents.

Three execution modes:
  A. VBScript bridge  — generates a .vbs COM-automation wrapper (no pre-embedded macro needed)
  B. winword.exe /m   — invokes Word CLI to run a pre-embedded named macro
  C. pywin32 COM      — direct win32com automation (Windows + pywin32 required)

Utility helpers:
  write_bas_file()        Save VBA code as a standard .bas module file
  build_auto_open_stub()  Generate an AutoOpen Sub that calls a named Sub
  check_winword()         Verify winword.exe is on PATH
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Optional

_BAS_HEADER = 'Attribute VB_Name = "AutoModule"\nOption Explicit\n'


def check_winword() -> str:
    """Return the absolute path to winword.exe if found on PATH, else empty string."""
    return shutil.which("winword") or shutil.which("winword.exe") or shutil.which("WINWORD") or ""


def write_bas_file(vba_code: str, path: str | Path) -> Path:
    """Write vba_code to a .bas module file with the standard VBA module header."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_BAS_HEADER + "\n" + vba_code.lstrip("\n"), encoding="utf-8")
    return out


def build_auto_open_stub(sub_name: str) -> str:
    """Return a VBA AutoOpen Sub that calls sub_name when the document opens."""
    return textwrap.dedent(f"""\
        Sub AutoOpen()
            {sub_name}
        End Sub
    """)


def generate_vbs_runner(
    doc_path: str,
    vba_code: str,
    sub_name: str,
    out_path: str | Path,
) -> Path:
    """
    Write a .vbs script that opens doc_path via COM, injects vba_code as a new
    VBA module, runs sub_name, saves, and closes.

    Requirements: Windows, Word installed, Trust Center → "Trust access to the
    VBA project object model" enabled.
    """
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    escaped_code = vba_code.replace('"', '""').replace("\r\n", "\n").replace("\n", '" & Chr(10) & "')

    vbs = textwrap.dedent(f"""\
        ' VBA runner generated by vba_runner.py
        ' Requirements: Windows, Word installed, VBA project model access enabled
        Option Explicit

        Dim oWord, oDoc, oModule, sCode

        sCode = "{escaped_code}"

        Set oWord = CreateObject("Word.Application")
        oWord.Visible = False

        Set oDoc = oWord.Documents.Open("{doc_path}")

        Set oModule = oDoc.VBProject.VBComponents.Add(1)
        oModule.CodeModule.AddFromString sCode

        oWord.Run "{sub_name}"

        oDoc.Save
        oDoc.Close False
        oWord.Quit

        Set oModule = Nothing
        Set oDoc = Nothing
        Set oWord = Nothing

        WScript.Echo "Done: {sub_name} completed on {doc_path}"
    """)

    out.write_text(vbs, encoding="utf-8")
    return out


def invoke_winword(
    doc_path: str,
    macro_name: Optional[str] = None,
    template_path: Optional[str] = None,
    no_splash: bool = False,
    suppress_autoexec: bool = False,
    disable_addins: bool = False,
) -> subprocess.CompletedProcess:
    """
    Build and run a winword.exe command with the given switches.

      /m<macroname>   Run named macro; also suppresses AutoExec macros
      /m              Suppress AutoExec macros only (no macro name)
      /ttemplatename  Open new document based on template (no space before name)
      /q              Hide the Word splash screen (does NOT suppress macros)
      /a              Disable all add-ins and global templates (locks setting files)

    Raises FileNotFoundError if winword.exe is not on PATH.
    """
    winword = check_winword()
    if not winword:
        raise FileNotFoundError(
            "winword.exe not found on PATH. "
            "Add the Office bin directory to PATH and retry."
        )
    cmd: list[str] = [winword]
    if disable_addins:
        cmd.append("/a")
    if no_splash:
        cmd.append("/q")
    if template_path:
        cmd.append(f"/t{template_path}")
    if macro_name:
        cmd.append(f"/m{macro_name}")
    elif suppress_autoexec:
        cmd.append("/m")
    if doc_path:
        cmd.append(doc_path)
    return subprocess.run(cmd, check=False, capture_output=True, text=True)


def run_via_com(doc_path: str, vba_code: str, sub_name: str) -> dict:
    """
    Inject vba_code into doc_path and run sub_name using win32com.

    Returns {"success": bool, "output": str, "error": str}.
    Requires: pip install pywin32, Windows, Word installed.
    """
    try:
        import win32com.client  # type: ignore[import-untyped]
    except ImportError:
        return {
            "success": False,
            "output": "",
            "error": "pywin32 not installed. Run: pip install pywin32",
        }
    try:
        word = win32com.client.Dispatch("Word.Application")
        word.Visible = False
        doc = word.Documents.Open(str(Path(doc_path).resolve()))
        module = doc.VBProject.VBComponents.Add(1)
        module.CodeModule.AddFromString(vba_code)
        word.Run(sub_name)
        doc.Save()
        doc.Close(False)
        word.Quit()
        return {"success": True, "output": f"{sub_name} completed on {doc_path}", "error": ""}
    except Exception as exc:  # noqa: BLE001
        return {"success": False, "output": "", "error": str(exc)}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cli() -> int:
    parser = argparse.ArgumentParser(
        description="VBA macro generation and Word automation helpers",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              python vba_runner.py check
              python vba_runner.py write-bas --code my_macro.vba --out module.bas
              python vba_runner.py generate-vbs --doc report.docx --code macro.vba --sub RunReport
              python vba_runner.py invoke --doc report.docm --macro RunReport
              python vba_runner.py invoke --doc input.docx --template automation.dotm
              python vba_runner.py run-com --doc report.docx --code macro.vba --sub RunReport
        """),
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("check", help="Verify winword.exe is on PATH")

    p_bas = sub.add_parser("write-bas", help="Save VBA code as a .bas module file")
    p_bas.add_argument("--code", required=True, help="Path to .vba source file")
    p_bas.add_argument("--out", required=True, help="Destination .bas file path")

    p_gen = sub.add_parser("generate-vbs", help="Generate a VBScript COM runner")
    p_gen.add_argument("--doc", required=True, help="Target .docx/.docm path")
    p_gen.add_argument("--code", required=True, help="Path to .vba source file")
    p_gen.add_argument("--sub", required=True, help="VBA Sub name to run")
    p_gen.add_argument("--out", default="run_macro.vbs", help="Output .vbs path (default: run_macro.vbs)")

    p_inv = sub.add_parser("invoke", help="Run winword.exe with CLI switches")
    p_inv.add_argument("--doc", default="", help="Document path")
    p_inv.add_argument("--macro", default=None, help="Macro name for /m switch")
    p_inv.add_argument("--template", default=None, help="Template path for /t switch")
    p_inv.add_argument("--no-splash", action="store_true", help="Hide splash screen with /q")
    p_inv.add_argument("--suppress-autoexec", action="store_true", help="Suppress AutoExec macros with /m")
    p_inv.add_argument("--no-addins", action="store_true", help="Disable add-ins with /a")

    p_com = sub.add_parser("run-com", help="Run VBA via win32com (Windows + pywin32)")
    p_com.add_argument("--doc", required=True, help="Target .docx/.docm path")
    p_com.add_argument("--code", required=True, help="Path to .vba source file")
    p_com.add_argument("--sub", required=True, help="VBA Sub name to run")

    args = parser.parse_args()

    if args.command == "check":
        path = check_winword()
        if path:
            print(f"winword.exe found: {path}")
            return 0
        print("winword.exe NOT found on PATH.")
        return 1

    if args.command == "write-bas":
        code = Path(args.code).read_text(encoding="utf-8")
        out = write_bas_file(code, args.out)
        print(f"Wrote .bas module: {out}")
        return 0

    if args.command == "generate-vbs":
        code = Path(args.code).read_text(encoding="utf-8")
        out = generate_vbs_runner(args.doc, code, args.sub, args.out)
        print(f"Generated VBScript runner: {out}")
        return 0

    if args.command == "invoke":
        try:
            result = invoke_winword(
                args.doc,
                macro_name=args.macro,
                template_path=args.template,
                no_splash=args.no_splash,
                suppress_autoexec=args.suppress_autoexec,
                disable_addins=args.no_addins,
            )
        except FileNotFoundError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            return 1
        print(f"Return code: {result.returncode}")
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        return result.returncode

    if args.command == "run-com":
        code = Path(args.code).read_text(encoding="utf-8")
        result = run_via_com(args.doc, code, args.sub)
        if result["success"]:
            print(result["output"])
            return 0
        print(f"Error: {result['error']}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(_cli())
