"""
vba_runner.py - VBA macro generation and execution helpers for PowerPoint presentations.

Three execution modes:
  A. VBScript bridge  — generates a .vbs COM-automation wrapper (no pre-embedded macro needed)
  B. POWERPNT.exe /M  — opens a .pptm via CLI and runs a pre-embedded named macro
  C. pywin32 COM      — direct win32com automation (Windows + pywin32 required)

Unlike Excel, PowerPoint supports /M <file> "<MacroName>" to run a named macro on launch.
The presentation file must be macro-enabled (.pptm).

PowerPoint has no Auto_Open Sub. Use Presentation_Open in ThisPresentation instead:
  Private Sub Presentation_Open()
      MyMacroName
  End Sub

PowerPoint COM automation typically requires Visible = True; fully headless operation
is unreliable.

Utility helpers:
  write_bas_file()              Save VBA code as a standard .bas module file
  build_presentation_open_stub()  Generate a Presentation_Open Sub that calls a named Sub
  check_powerpnt()              Verify POWERPNT.exe is on PATH
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Optional

_BAS_HEADER = 'Attribute VB_Name = "AutoModule"\nOption Explicit\n'


def check_powerpnt() -> str:
    """Return the absolute path to POWERPNT.exe if found on PATH, else empty string."""
    return (
        shutil.which("powerpnt")
        or shutil.which("powerpnt.exe")
        or shutil.which("POWERPNT")
        or shutil.which("POWERPNT.EXE")
        or ""
    )


def write_bas_file(vba_code: str, path: str | Path) -> Path:
    """Write vba_code to a .bas module file with the standard VBA module header."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_BAS_HEADER + "\n" + vba_code.lstrip("\n"), encoding="utf-8")
    return out


def build_presentation_open_stub(sub_name: str) -> str:
    """Return a Presentation_Open Sub in ThisPresentation that calls sub_name.

    PowerPoint has no Auto_Open equivalent in standard modules. Presentation_Open
    (in the ThisPresentation class module) fires when the presentation opens for
    both interactive and programmatic opens.
    """
    return textwrap.dedent(f"""\
        Private Sub Presentation_Open()
            {sub_name}
        End Sub
    """)


def generate_vbs_runner(
    prs_path: str,
    vba_code: str,
    sub_name: str,
    out_path: str | Path,
) -> Path:
    """
    Write a .vbs script that opens prs_path via COM, injects vba_code as a new
    VBA module, runs sub_name via Application.Run, saves, and closes.

    Requirements: Windows, PowerPoint installed, Visible = True (PowerPoint COM
    requires visibility), Trust Center → "Trust access to the VBA project object
    model" enabled.
    """
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    escaped_code = vba_code.replace('"', '""').replace("\r\n", "\n").replace("\n", '" & Chr(10) & "')

    vbs = textwrap.dedent(f"""\
        ' VBA runner generated by vba_runner.py
        ' Requirements: Windows, PowerPoint installed, VBA project model access enabled
        Option Explicit

        Dim oPPT, oPrs, oModule, sCode

        sCode = "{escaped_code}"

        Set oPPT = CreateObject("PowerPoint.Application")
        oPPT.Visible = True

        Set oPrs = oPPT.Presentations.Open("{prs_path}")

        Set oModule = oPrs.VBProject.VBComponents.Add(1)
        oModule.CodeModule.AddFromString sCode

        oPPT.Run "{sub_name}"

        oPrs.Save
        oPrs.Close
        oPPT.Quit

        Set oModule = Nothing
        Set oPrs = Nothing
        Set oPPT = Nothing

        WScript.Echo "Done: {sub_name} completed on {prs_path}"
    """)

    out.write_text(vbs, encoding="utf-8")
    return out


def invoke_powerpnt(
    prs_path: str = "",
    macro_name: Optional[str] = None,
    new_blank: bool = False,
    new_from_template: Optional[str] = None,
    slide_show: bool = False,
    embedding: bool = False,
) -> subprocess.CompletedProcess:
    """
    Build and run a POWERPNT.exe command with the given switches.

      /B              Start with a new blank presentation
      /M <file> <macro>  Open file and run the named macro (file must be .pptm)
      /N [template]   New presentation, optionally based on a .potx template
      /S <file>       Open file as a slide show
      /EMBEDDING      No program window (add-in testing)

    The /M switch syntax is: POWERPNT.exe /M <prs_path> "<macro_name>"
    Note the file path comes immediately after /M, macro name is a separate arg.

    Raises FileNotFoundError if POWERPNT.exe is not on PATH.
    """
    powerpnt = check_powerpnt()
    if not powerpnt:
        raise FileNotFoundError(
            "POWERPNT.exe not found on PATH. "
            "Add the Office bin directory to PATH and retry."
        )
    cmd: list[str] = [powerpnt]

    if embedding:
        cmd.append("/EMBEDDING")

    if macro_name and prs_path:
        cmd.extend(["/M", prs_path, macro_name])
    elif slide_show and prs_path:
        cmd.extend(["/S", prs_path])
    elif new_from_template:
        cmd.extend(["/N", new_from_template])
    elif new_blank:
        cmd.append("/B")
    elif prs_path:
        cmd.append(prs_path)

    return subprocess.run(cmd, check=False, capture_output=True, text=True)


def run_via_com(prs_path: str, vba_code: str, sub_name: str) -> dict:
    """
    Inject vba_code into prs_path and run sub_name using win32com.

    Returns {"success": bool, "output": str, "error": str}.
    Requires: pip install pywin32, Windows, PowerPoint installed.

    Note: PowerPoint COM requires Visible = True; headless operation is unreliable.
    """
    try:
        import win32com.client  # type: ignore[import-untyped]
    except ImportError:
        return {
            "success": False,
            "output": "",
            "error": "pywin32 not installed. Run: pip install pywin32",
        }
    try:
        ppt = win32com.client.Dispatch("PowerPoint.Application")
        ppt.Visible = True
        prs = ppt.Presentations.Open(str(Path(prs_path).resolve()))
        module = prs.VBProject.VBComponents.Add(1)
        module.CodeModule.AddFromString(vba_code)
        ppt.Run(sub_name)
        prs.Save()
        prs.Close()
        ppt.Quit()
        return {"success": True, "output": f"{sub_name} completed on {prs_path}", "error": ""}
    except Exception as exc:  # noqa: BLE001
        return {"success": False, "output": "", "error": str(exc)}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cli() -> int:
    parser = argparse.ArgumentParser(
        description="VBA macro generation and PowerPoint automation helpers",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              python vba_runner.py check
              python vba_runner.py write-bas --code my_macro.vba --out module.bas
              python vba_runner.py generate-vbs --prs report.pptx --code macro.vba --sub BuildSlides
              python vba_runner.py invoke --prs report.pptm --macro BuildSlides
              python vba_runner.py invoke --prs keynote.pptx --slide-show
              python vba_runner.py run-com --prs report.pptx --code macro.vba --sub BuildSlides
        """),
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("check", help="Verify POWERPNT.exe is on PATH")

    p_bas = sub.add_parser("write-bas", help="Save VBA code as a .bas module file")
    p_bas.add_argument("--code", required=True, help="Path to .vba source file")
    p_bas.add_argument("--out", required=True, help="Destination .bas file path")

    p_gen = sub.add_parser("generate-vbs", help="Generate a VBScript COM runner")
    p_gen.add_argument("--prs", required=True, help="Target .pptx/.pptm path")
    p_gen.add_argument("--code", required=True, help="Path to .vba source file")
    p_gen.add_argument("--sub", required=True, help="VBA Sub name to run")
    p_gen.add_argument("--out", default="run_macro.vbs", help="Output .vbs path (default: run_macro.vbs)")

    p_inv = sub.add_parser("invoke", help="Run POWERPNT.exe with CLI switches")
    p_inv.add_argument("--prs", default="", help="Presentation path")
    p_inv.add_argument("--macro", default=None, help="Macro name for /M switch (requires .pptm)")
    p_inv.add_argument("--new-blank", action="store_true", help="New blank presentation with /B")
    p_inv.add_argument("--template", default=None, help="Template path for /N switch")
    p_inv.add_argument("--slide-show", action="store_true", help="Open as slide show with /S")
    p_inv.add_argument("--embedding", action="store_true", help="No program window with /EMBEDDING")

    p_com = sub.add_parser("run-com", help="Run VBA via win32com (Windows + pywin32)")
    p_com.add_argument("--prs", required=True, help="Target .pptx/.pptm path")
    p_com.add_argument("--code", required=True, help="Path to .vba source file")
    p_com.add_argument("--sub", required=True, help="VBA Sub name to run")

    args = parser.parse_args()

    if args.command == "check":
        path = check_powerpnt()
        if path:
            print(f"POWERPNT.exe found: {path}")
            return 0
        print("POWERPNT.exe NOT found on PATH.")
        return 1

    if args.command == "write-bas":
        code = Path(args.code).read_text(encoding="utf-8")
        out = write_bas_file(code, args.out)
        print(f"Wrote .bas module: {out}")
        return 0

    if args.command == "generate-vbs":
        code = Path(args.code).read_text(encoding="utf-8")
        out = generate_vbs_runner(args.prs, code, args.sub, args.out)
        print(f"Generated VBScript runner: {out}")
        return 0

    if args.command == "invoke":
        try:
            result = invoke_powerpnt(
                prs_path=args.prs,
                macro_name=args.macro,
                new_blank=args.new_blank,
                new_from_template=args.template,
                slide_show=args.slide_show,
                embedding=args.embedding,
            )
        except FileNotFoundError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            return 1
        print(f"Return code: {result.returncode}")
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        return result.returncode

    if args.command == "run-com":
        code = Path(args.code).read_text(encoding="utf-8")
        result = run_via_com(args.prs, code, args.sub)
        if result["success"]:
            print(result["output"])
            return 0
        print(f"Error: {result['error']}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(_cli())
