"""
vba_runner.py - VBA macro generation and execution helpers for Excel workbooks.

Three execution modes:
  A. VBScript bridge  — generates a .vbs COM-automation wrapper (no pre-embedded macro needed)
  B. excel.exe CLI    — opens workbook via CLI; relies on Auto_Open/Workbook_Open in the file
  C. pywin32 COM      — direct win32com automation (Windows + pywin32 required)

Excel has no /m<macroname> CLI switch (unlike Word). For macro execution without
an embedded macro, use Mode A or C. For Mode B, embed an Auto_Open or
Workbook_Open Sub in the workbook before invoking.

Utility helpers:
  write_bas_file()         Save VBA code as a standard .bas module file
  build_auto_open_stub()   Generate an Auto_Open Sub that calls a named Sub
  check_excel()            Verify excel.exe is on PATH
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Optional

_BAS_HEADER = 'Attribute VB_Name = "AutoModule"\nOption Explicit\n'


def check_excel() -> str:
    """Return the absolute path to excel.exe if found on PATH, else empty string."""
    return shutil.which("excel") or shutil.which("excel.exe") or shutil.which("EXCEL") or ""


def write_bas_file(vba_code: str, path: str | Path) -> Path:
    """Write vba_code to a .bas module file with the standard VBA module header."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_BAS_HEADER + "\n" + vba_code.lstrip("\n"), encoding="utf-8")
    return out


def build_auto_open_stub(sub_name: str) -> str:
    """Return a VBA Auto_Open Sub that calls sub_name when the workbook opens.

    Auto_Open works in standard modules and fires for both interactive and
    programmatic opens. For Workbook_Open (ThisWorkbook module), see the
    references/vba-docs/Workbooks-and-Worksheets/ docs.
    """
    return textwrap.dedent(f"""\
        Sub Auto_Open()
            {sub_name}
        End Sub
    """)


def generate_vbs_runner(
    wb_path: str,
    vba_code: str,
    sub_name: str,
    out_path: str | Path,
) -> Path:
    """
    Write a .vbs script that opens wb_path via COM, injects vba_code as a new
    VBA module, runs sub_name via Application.Run, saves, and closes.

    Requirements: Windows, Excel installed, Trust Center → "Trust access to the
    VBA project object model" enabled.
    """
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    escaped_code = vba_code.replace('"', '""').replace("\r\n", "\n").replace("\n", '" & Chr(10) & "')

    vbs = textwrap.dedent(f"""\
        ' VBA runner generated by vba_runner.py
        ' Requirements: Windows, Excel installed, VBA project model access enabled
        Option Explicit

        Dim oExcel, oWb, oModule, sCode

        sCode = "{escaped_code}"

        Set oExcel = CreateObject("Excel.Application")
        oExcel.Visible = False
        oExcel.DisplayAlerts = False

        Set oWb = oExcel.Workbooks.Open("{wb_path}")

        Set oModule = oWb.VBProject.VBComponents.Add(1)
        oModule.CodeModule.AddFromString sCode

        oExcel.Run "{sub_name}"

        oWb.Save
        oWb.Close False
        oExcel.Quit

        Set oModule = Nothing
        Set oWb = Nothing
        Set oExcel = Nothing

        WScript.Echo "Done: {sub_name} completed on {wb_path}"
    """)

    out.write_text(vbs, encoding="utf-8")
    return out


def invoke_excel(
    wb_path: str = "",
    read_only: bool = False,
    as_template: bool = False,
    safe: bool = False,
    new_instance: bool = False,
    working_dir: Optional[str] = None,
    embed: bool = False,
) -> subprocess.CompletedProcess:
    """
    Build and run an excel.exe command with the given switches.

      /r              Open workbook as read-only
      /t              Open workbook as a template
      /s              Bypass XLStart startup directories (safe mode)
      /x              Start a new isolated Excel instance
      /p "path"       Set active working folder
      /e              Suppress startup screen and blank workbook

    Note: Excel has no /m<macroname> switch. Use generate_vbs_runner() or
    run_via_com() to execute a specific macro programmatically.

    Raises FileNotFoundError if excel.exe is not on PATH.
    """
    excel = check_excel()
    if not excel:
        raise FileNotFoundError(
            "excel.exe not found on PATH. "
            "Add the Office bin directory to PATH and retry."
        )
    cmd: list[str] = [excel]
    if embed:
        cmd.append("/e")
    if safe:
        cmd.append("/s")
    if working_dir:
        cmd.extend(["/p", working_dir])
    if new_instance and wb_path:
        cmd.append("/x")
        cmd.append(wb_path)
    elif as_template and wb_path:
        cmd.append("/t")
        cmd.append(wb_path)
    elif read_only and wb_path:
        cmd.append("/r")
        cmd.append(wb_path)
    elif wb_path:
        cmd.append(wb_path)
    return subprocess.run(cmd, check=False, capture_output=True, text=True)


def run_via_com(wb_path: str, vba_code: str, sub_name: str) -> dict:
    """
    Inject vba_code into wb_path and run sub_name using win32com.

    Returns {"success": bool, "output": str, "error": str}.
    Requires: pip install pywin32, Windows, Excel installed.
    """
    try:
        import win32com.client  # type: ignore[import-untyped]
    except ImportError:
        return {
            "success": False,
            "output": "",
            "error": "pywin32 not installed. Run: pip install pywin32",
        }
    try:
        excel = win32com.client.Dispatch("Excel.Application")
        excel.Visible = False
        excel.DisplayAlerts = False
        wb = excel.Workbooks.Open(str(Path(wb_path).resolve()))
        module = wb.VBProject.VBComponents.Add(1)
        module.CodeModule.AddFromString(vba_code)
        excel.Run(sub_name)
        wb.Save()
        wb.Close(False)
        excel.Quit()
        return {"success": True, "output": f"{sub_name} completed on {wb_path}", "error": ""}
    except Exception as exc:  # noqa: BLE001
        return {"success": False, "output": "", "error": str(exc)}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cli() -> int:
    parser = argparse.ArgumentParser(
        description="VBA macro generation and Excel automation helpers",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              python vba_runner.py check
              python vba_runner.py write-bas --code my_macro.vba --out module.bas
              python vba_runner.py generate-vbs --wb report.xlsx --code macro.vba --sub RunReport
              python vba_runner.py invoke --wb report.xlsm
              python vba_runner.py invoke --wb data.xlsx --read-only
              python vba_runner.py invoke --wb data.xlsx --safe
              python vba_runner.py run-com --wb report.xlsx --code macro.vba --sub RunReport
        """),
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("check", help="Verify excel.exe is on PATH")

    p_bas = sub.add_parser("write-bas", help="Save VBA code as a .bas module file")
    p_bas.add_argument("--code", required=True, help="Path to .vba source file")
    p_bas.add_argument("--out", required=True, help="Destination .bas file path")

    p_gen = sub.add_parser("generate-vbs", help="Generate a VBScript COM runner")
    p_gen.add_argument("--wb", required=True, help="Target .xlsx/.xlsm path")
    p_gen.add_argument("--code", required=True, help="Path to .vba source file")
    p_gen.add_argument("--sub", required=True, help="VBA Sub name to run")
    p_gen.add_argument("--out", default="run_macro.vbs", help="Output .vbs path (default: run_macro.vbs)")

    p_inv = sub.add_parser("invoke", help="Run excel.exe with CLI switches")
    p_inv.add_argument("--wb", default="", help="Workbook path")
    p_inv.add_argument("--read-only", action="store_true", help="Open read-only with /r")
    p_inv.add_argument("--template", action="store_true", help="Open as template with /t")
    p_inv.add_argument("--safe", action="store_true", help="Bypass XLStart with /s")
    p_inv.add_argument("--new-instance", action="store_true", help="New Excel process with /x")
    p_inv.add_argument("--working-dir", default=None, help="Set working folder with /p")
    p_inv.add_argument("--embed", action="store_true", help="Suppress startup screen with /e")

    p_com = sub.add_parser("run-com", help="Run VBA via win32com (Windows + pywin32)")
    p_com.add_argument("--wb", required=True, help="Target .xlsx/.xlsm path")
    p_com.add_argument("--code", required=True, help="Path to .vba source file")
    p_com.add_argument("--sub", required=True, help="VBA Sub name to run")

    args = parser.parse_args()

    if args.command == "check":
        path = check_excel()
        if path:
            print(f"excel.exe found: {path}")
            return 0
        print("excel.exe NOT found on PATH.")
        return 1

    if args.command == "write-bas":
        code = Path(args.code).read_text(encoding="utf-8")
        out = write_bas_file(code, args.out)
        print(f"Wrote .bas module: {out}")
        return 0

    if args.command == "generate-vbs":
        code = Path(args.code).read_text(encoding="utf-8")
        out = generate_vbs_runner(args.wb, code, args.sub, args.out)
        print(f"Generated VBScript runner: {out}")
        return 0

    if args.command == "invoke":
        try:
            result = invoke_excel(
                wb_path=args.wb,
                read_only=args.read_only,
                as_template=args.template,
                safe=args.safe,
                new_instance=args.new_instance,
                working_dir=args.working_dir,
                embed=args.embed,
            )
        except FileNotFoundError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            return 1
        print(f"Return code: {result.returncode}")
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        return result.returncode

    if args.command == "run-com":
        code = Path(args.code).read_text(encoding="utf-8")
        result = run_via_com(args.wb, code, args.sub)
        if result["success"]:
            print(result["output"])
            return 0
        print(f"Error: {result['error']}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(_cli())
